import { Ad } from '@/types/ad'
import { getScoreLabel } from '@/lib/enrichment/performance-scorer'

type SeedAd = Omit<Ad, 'id' | 'created_at' | 'scraped_at'>

// Realistic demo ads matching actual Supabase `ads` table schema
const MOCK_ADS: SeedAd[] = [
  // === TRAVEL ===
  {
    advertiser_name: 'Airbnb', status: 'ACTIVE', media_type: 'video',
    primary_text: 'Vive una experiencia única en los mejores alojamientos del Perú. Desde soles 89/noche.',
    headline: 'Encuentra tu hogar en Perú',
    image_url: 'https://picsum.photos/seed/airbnb-pe/400/700',
    start_date: '2025-12-01T00:00:00Z',
    publisher_platforms: ['facebook', 'instagram'],
    performance_score: 88, estimated_spend_min: 1200, estimated_spend_max: 4800,
    raw_data: { country_code: 'PE', industry: 'travel', creatives_count: 4, score_label: getScoreLabel(88) },
  },
  {
    advertiser_name: 'Airbnb', status: 'ACTIVE', media_type: 'image',
    primary_text: '¿Listo para tu próxima aventura? Descubre alojamientos únicos en México desde $450 MXN/noche.',
    headline: 'Hospedaje único en México',
    image_url: 'https://picsum.photos/seed/airbnb-mx/400/700',
    start_date: '2025-11-15T00:00:00Z',
    publisher_platforms: ['facebook', 'instagram', 'messenger'],
    performance_score: 82, estimated_spend_min: 900, estimated_spend_max: 3600,
    raw_data: { country_code: 'MX', industry: 'travel', creatives_count: 3, score_label: getScoreLabel(82) },
  },
  {
    advertiser_name: 'Booking.com', status: 'ACTIVE', media_type: 'carousel',
    primary_text: 'Reserva tu hotel con cancelación gratuita. Sin cargos ocultos. Más de 28 millones de alojamientos.',
    headline: 'Reserva hoteles — sin pago por adelantado',
    image_url: 'https://picsum.photos/seed/booking-ar/400/700',
    start_date: '2025-10-01T00:00:00Z',
    publisher_platforms: ['facebook', 'instagram'],
    performance_score: 91, estimated_spend_min: 2000, estimated_spend_max: 8000,
    raw_data: { country_code: 'AR', industry: 'travel', creatives_count: 6, score_label: getScoreLabel(91) },
  },
  {
    advertiser_name: 'Despegar', status: 'INACTIVE', media_type: 'image',
    primary_text: 'Vuelos a Miami desde COP 890.000. ¡Solo por tiempo limitado! Comparamos miles de opciones.',
    headline: 'Vuelos baratos Colombia → USA',
    image_url: 'https://picsum.photos/seed/despegar-co/400/700',
    start_date: '2025-09-01T00:00:00Z', end_date: '2025-11-30T00:00:00Z',
    publisher_platforms: ['facebook'],
    performance_score: 76, estimated_spend_min: 600, estimated_spend_max: 2400,
    raw_data: { country_code: 'CO', industry: 'travel', creatives_count: 2, score_label: getScoreLabel(76) },
  },
  {
    advertiser_name: 'Booking.com', status: 'ACTIVE', media_type: 'image',
    primary_text: '¿Listo para tu próximo viaje? Encuentra hoteles con cancelación gratis hasta 24h antes.',
    headline: 'Hoteles con cancelación gratis',
    image_url: 'https://picsum.photos/seed/booking-mx/400/700',
    start_date: '2025-12-01T00:00:00Z',
    publisher_platforms: ['facebook', 'instagram'],
    performance_score: 80, estimated_spend_min: 1000, estimated_spend_max: 4000,
    raw_data: { country_code: 'MX', industry: 'travel', creatives_count: 4, score_label: getScoreLabel(80) },
  },

  // === FINTECH ===
  {
    advertiser_name: 'Nu México', status: 'ACTIVE', media_type: 'video',
    primary_text: 'La tarjeta de crédito sin comisiones anuales. Sin letra pequeña. Solo beneficios reales.',
    headline: 'Tu primera tarjeta sin comisiones',
    image_url: 'https://picsum.photos/seed/nubank-mx/400/700',
    start_date: '2025-08-01T00:00:00Z',
    publisher_platforms: ['facebook', 'instagram', 'whatsapp_business'],
    performance_score: 94, estimated_spend_min: 3000, estimated_spend_max: 12000,
    raw_data: { country_code: 'MX', industry: 'fintech', creatives_count: 8, score_label: getScoreLabel(94) },
  },
  {
    advertiser_name: 'Mercado Pago', status: 'ACTIVE', media_type: 'video',
    primary_text: 'Recibe pagos con tarjeta sin necesidad de punto de venta. Cobra desde tu celular.',
    headline: 'Cobra con tu celular',
    image_url: 'https://picsum.photos/seed/mercadopago-ar/400/700',
    start_date: '2025-07-15T00:00:00Z',
    publisher_platforms: ['facebook', 'instagram'],
    performance_score: 87, estimated_spend_min: 1800, estimated_spend_max: 7200,
    raw_data: { country_code: 'AR', industry: 'fintech', creatives_count: 5, score_label: getScoreLabel(87) },
  },
  {
    advertiser_name: 'Rappi', status: 'ACTIVE', media_type: 'carousel',
    primary_text: '¡RappiPay te da hasta 10% de cashback en tu primera compra! Descárgalo ahora.',
    headline: 'Cashback real con RappiPay',
    image_url: 'https://picsum.photos/seed/rappi-co/400/700',
    start_date: '2025-10-20T00:00:00Z',
    publisher_platforms: ['facebook', 'instagram'],
    performance_score: 79, estimated_spend_min: 800, estimated_spend_max: 3200,
    raw_data: { country_code: 'CO', industry: 'fintech', creatives_count: 4, score_label: getScoreLabel(79) },
  },
  {
    advertiser_name: 'Rappi', status: 'ACTIVE', media_type: 'video',
    primary_text: '¿Hambre? Pide en Rappi y recibe en 30 min. Primer pedido con 50% de descuento.',
    headline: 'Delivery en 30 minutos',
    image_url: 'https://picsum.photos/seed/rappi-mx/400/700',
    start_date: '2025-11-01T00:00:00Z',
    publisher_platforms: ['facebook', 'instagram'],
    performance_score: 83, estimated_spend_min: 1200, estimated_spend_max: 4800,
    raw_data: { country_code: 'MX', industry: 'fintech', creatives_count: 5, score_label: getScoreLabel(83) },
  },

  // === ECOMMERCE ===
  {
    advertiser_name: 'SHEIN', status: 'ACTIVE', media_type: 'video',
    primary_text: 'Moda a precios increíbles. Envío gratis en pedidos mayores a $299 MXN. ¡Nuevos estilos cada día!',
    headline: 'Ropa trendy desde $29 MXN',
    image_url: 'https://picsum.photos/seed/shein-mx/400/700',
    start_date: '2025-06-01T00:00:00Z',
    publisher_platforms: ['facebook', 'instagram'],
    performance_score: 92, estimated_spend_min: 2500, estimated_spend_max: 10000,
    raw_data: { country_code: 'MX', industry: 'ecommerce', creatives_count: 12, score_label: getScoreLabel(92) },
  },
  {
    advertiser_name: 'Temu', status: 'ACTIVE', media_type: 'video',
    primary_text: 'Shop like a billionaire. Free shipping on orders over $0. 90-day free returns.',
    headline: 'Millions of products, lowest prices',
    image_url: 'https://picsum.photos/seed/temu-us/400/700',
    start_date: '2025-05-01T00:00:00Z',
    publisher_platforms: ['facebook', 'instagram', 'messenger'],
    performance_score: 89, estimated_spend_min: 5000, estimated_spend_max: 20000,
    raw_data: { country_code: 'US', industry: 'ecommerce', creatives_count: 15, score_label: getScoreLabel(89) },
  },
  {
    advertiser_name: 'ZARA', status: 'ACTIVE', media_type: 'image',
    primary_text: 'La nueva colección ya está disponible. Visita nuestra tienda online.',
    headline: 'Nueva colección ZARA',
    image_url: 'https://picsum.photos/seed/zara-pe/400/700',
    start_date: '2026-01-15T00:00:00Z',
    publisher_platforms: ['facebook', 'instagram'],
    performance_score: 72, estimated_spend_min: 500, estimated_spend_max: 2000,
    raw_data: { country_code: 'PE', industry: 'ecommerce', creatives_count: 3, score_label: getScoreLabel(72) },
  },
  {
    advertiser_name: 'H&M', status: 'ACTIVE', media_type: 'carousel',
    primary_text: 'New arrivals every week. Sustainable fashion at affordable prices.',
    headline: 'Fashion & Quality at the best price',
    image_url: 'https://picsum.photos/seed/hm-us/400/700',
    start_date: '2025-10-01T00:00:00Z',
    publisher_platforms: ['facebook', 'instagram'],
    performance_score: 70, estimated_spend_min: 800, estimated_spend_max: 3200,
    raw_data: { country_code: 'US', industry: 'ecommerce', creatives_count: 6, score_label: getScoreLabel(70) },
  },

  // === EDUCATION ===
  {
    advertiser_name: 'Duolingo', status: 'ACTIVE', media_type: 'video',
    primary_text: 'Aprende inglés en solo 5 minutos al día. Gratis para siempre. ¡Más de 500 millones de usuarios!',
    headline: 'Aprende inglés gratis',
    image_url: 'https://picsum.photos/seed/duolingo/400/700',
    start_date: '2025-09-01T00:00:00Z',
    publisher_platforms: ['facebook', 'instagram'],
    performance_score: 86, estimated_spend_min: 1500, estimated_spend_max: 6000,
    raw_data: { country_code: 'CO', industry: 'education', creatives_count: 7, score_label: getScoreLabel(86) },
  },
  {
    advertiser_name: 'Platzi', status: 'ACTIVE', media_type: 'video',
    primary_text: 'Aprende programación, diseño y marketing digital con los mejores profesores de América Latina.',
    headline: 'El mejor lugar para aprender tech',
    image_url: 'https://picsum.photos/seed/platzi-mx/400/700',
    start_date: '2025-10-01T00:00:00Z',
    publisher_platforms: ['facebook', 'instagram'],
    performance_score: 81, estimated_spend_min: 1000, estimated_spend_max: 4000,
    raw_data: { country_code: 'MX', industry: 'education', creatives_count: 6, score_label: getScoreLabel(81) },
  },
  {
    advertiser_name: 'Coursera', status: 'ACTIVE', media_type: 'image',
    primary_text: 'Certificados de Google, IBM y más. Aprende habilidades que los empleadores buscan.',
    headline: 'Certificaciones profesionales online',
    image_url: 'https://picsum.photos/seed/coursera-pe/400/700',
    start_date: '2025-11-01T00:00:00Z',
    publisher_platforms: ['facebook', 'linkedin'],
    performance_score: 75, estimated_spend_min: 600, estimated_spend_max: 2400,
    raw_data: { country_code: 'PE', industry: 'education', creatives_count: 3, score_label: getScoreLabel(75) },
  },

  // === TECH / SAAS ===
  {
    advertiser_name: 'Canva', status: 'ACTIVE', media_type: 'video',
    primary_text: 'Diseña como un profesional en minutos. Más de 2 millones de plantillas. ¡Gratis para siempre!',
    headline: 'El diseño al alcance de todos',
    start_date: '2025-08-15T00:00:00Z',
    publisher_platforms: ['facebook', 'instagram'],
    performance_score: 90, estimated_spend_min: 2000, estimated_spend_max: 8000,
    raw_data: { country_code: 'PE', industry: 'tech', creatives_count: 9, score_label: getScoreLabel(90) },
  },
  {
    advertiser_name: 'Canva', status: 'ACTIVE', media_type: 'carousel',
    primary_text: 'Design anything. Create stunning graphics, presentations and videos in minutes.',
    headline: 'Canva — Free Design Tool',
    image_url: 'https://picsum.photos/seed/canva-us/400/700',
    start_date: '2025-10-01T00:00:00Z',
    publisher_platforms: ['facebook', 'instagram', 'pinterest'],
    performance_score: 86, estimated_spend_min: 2500, estimated_spend_max: 10000,
    raw_data: { country_code: 'US', industry: 'tech', creatives_count: 8, score_label: getScoreLabel(86) },
  },
  {
    advertiser_name: 'Notion', status: 'ACTIVE', media_type: 'video',
    primary_text: 'The all-in-one workspace. Write, plan, collaborate, and organize — all in one tool.',
    headline: 'Replace all your apps with Notion',
    image_url: 'https://picsum.photos/seed/notion-us/400/700',
    start_date: '2025-07-01T00:00:00Z',
    publisher_platforms: ['facebook', 'instagram', 'linkedin'],
    performance_score: 85, estimated_spend_min: 1500, estimated_spend_max: 6000,
    raw_data: { country_code: 'US', industry: 'tech', creatives_count: 5, score_label: getScoreLabel(85) },
  },
  {
    advertiser_name: 'HubSpot', status: 'ACTIVE', media_type: 'carousel',
    primary_text: 'CRM gratuito para hacer crecer tu negocio. Automatiza ventas, marketing y atención al cliente.',
    headline: 'CRM gratuito para PyMES',
    image_url: 'https://picsum.photos/seed/hubspot-es/400/700',
    start_date: '2025-09-15T00:00:00Z',
    publisher_platforms: ['facebook', 'linkedin'],
    performance_score: 78, estimated_spend_min: 800, estimated_spend_max: 3200,
    raw_data: { country_code: 'ES', industry: 'tech', creatives_count: 4, score_label: getScoreLabel(78) },
  },

  // === FITNESS ===
  {
    advertiser_name: 'Nike', status: 'ACTIVE', media_type: 'video',
    primary_text: "Just Do It. The Nike Air Max 2025 is here. Limited stock. Shop now.",
    headline: 'Nike Air Max 2025',
    image_url: 'https://picsum.photos/seed/nike-us/400/700',
    start_date: '2026-01-01T00:00:00Z',
    publisher_platforms: ['facebook', 'instagram'],
    performance_score: 93, estimated_spend_min: 5000, estimated_spend_max: 20000,
    raw_data: { country_code: 'US', industry: 'fitness', creatives_count: 10, score_label: getScoreLabel(93) },
  },
  {
    advertiser_name: 'Adidas', status: 'ACTIVE', media_type: 'video',
    primary_text: 'Impossible is Nothing. New Ultraboost 2025 — engineered for every run.',
    headline: 'Ultraboost 2025 — Shop Now',
    image_url: 'https://picsum.photos/seed/adidas-us/400/700',
    start_date: '2025-12-15T00:00:00Z',
    publisher_platforms: ['facebook', 'instagram'],
    performance_score: 88, estimated_spend_min: 4000, estimated_spend_max: 16000,
    raw_data: { country_code: 'US', industry: 'fitness', creatives_count: 8, score_label: getScoreLabel(88) },
  },
  {
    advertiser_name: 'Nike', status: 'ACTIVE', media_type: 'image',
    primary_text: 'Entrena diferente. Las zapatillas Nike Pegasus ya están en Perú. Envío gratis.',
    headline: 'Nike Pegasus en Perú',
    image_url: 'https://picsum.photos/seed/nike-pe/400/700',
    start_date: '2026-02-01T00:00:00Z',
    publisher_platforms: ['facebook', 'instagram'],
    performance_score: 74, estimated_spend_min: 400, estimated_spend_max: 1600,
    raw_data: { country_code: 'PE', industry: 'fitness', creatives_count: 3, score_label: getScoreLabel(74) },
  },
]

export function getMockAds(): SeedAd[] {
  return MOCK_ADS
}
